Repository drivent-g14/drivent-front, pull requests merged in 2022-12, with the labels that each got.

#4 [FEAT] Tela de pagamentos - Modalidade de ingresso
  package-lock.json
  package.json
  src/components/Auth/index.js
  src/components/Dashboard/Containers/BoxContainer.js
  src/components/Dashboard/Containers/Container.js
  src/pages/Dashboard/Payment/index.js
Labels: feature, area/payments

#6 Feat/payment section
  package-lock.json
  package.json
  src/components/Dashboard/Buttons/FlatButton.js
  src/components/Dashboard/Containers/BoxContainer.js
  src/components/Dashboard/Sections/DisplaySection.js
  src/components/PaymentReservation/ReservationButton.js
  src/components/PaymentReservation/TicketReservation.js
  src/hooks/api/useTicket.js
  src/hooks/api/useTicketType.js
  src/pages/Dashboard/Payment/index.js
  src/services/ticketApi.js
Labels: feature, area/payments

#8 Feat/payment confirmation
  package-lock.json
  package.json
  src/components/Container.js
  src/components/PaymentForm/PaymentForm.js
  src/components/PaymentForm/PaymentValidation.js
  src/components/PaymentReservation/ReservationButton.js
  src/components/PaymentReservation/TicketReservation.js
  src/components/PersonalInformationForm/FormValidations.js
  src/hooks/api/usePayment.js
  src/hooks/api/useTicket.js
  src/hooks/useForm.js
  src/services/enrollmentApi.js
  src/services/paymentApi.js
  src/services/ticketApi.js
Labels: area/payments

#7 Feat/hotels cards
  .gitignore
  package-lock.json
  src/assets/images/hotels1.png
  src/assets/images/hotels2.png
  src/assets/images/hotels3.png
  src/components/Dashboard/Containers/CardContainer.js
  src/hooks/api/useHotels.js
  src/pages/Dashboard/Hotel/index.js
  src/services/hotelsApi.js
Labels: feat, area/hotels

#10 [FEAT] Integration
  package-lock.json
  src/components/Dashboard/Containers/BoxContainer.js
  src/components/Dashboard/Errors/UnauthorizedScreen.js
  src/components/PaymentForm/PaymentForm.js
  src/components/PaymentReservation/PaymentSection.js
  src/components/PaymentReservation/ReservationButton.js
  src/components/PaymentReservation/TicketReservation.js
  src/pages/Dashboard/Hotel/index.js
  src/pages/Dashboard/Payment/index.js
Labels: enhancement, feature
